[nfs_clients]
192.168.122.61 ansible_user=eng-reda ansible_ssh_private_key_file=~/.ssh/id_rsa

[local]
localhost ansible_user=reda ansible_password="you can do" ansible_connection=local

[nfs_servers]
 192.168.122.234 ansible_user=servera ansible_ssh_private_key_file=~/.ssh/id_rsa


